export const techStackLanguage: Array<Array<string>> = [
    ['https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white', 'Golang'],
    ['https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white', 'TypeScript'],
    ['https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E', 'JavaScript'],
    ['https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54', 'Python'],
    ['https://img.shields.io/badge/rust-%23000000.svg?style=for-the-badge&logo=rust&logoColor=white', 'Rust'],
    ['https://img.shields.io/badge/kotlin-%237F52FF.svg?style=for-the-badge&logo=kotlin&logoColor=white', 'Kotlin'],
    ['https://img.shields.io/badge/dart-%230175C2.svg?style=for-the-badge&logo=dart&logoColor=white', 'Dart'],
    ['https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white', 'Java'],
    ['https://img.shields.io/badge/c%23-%23239120.svg?style=for-the-badge&logo=csharp&logoColor=white', 'C#'],
    ['https://img.shields.io/badge/php-%23777BB4.svg?style=for-the-badge&logo=php&logoColor=white', 'PHP'],
    ['https://img.shields.io/badge/c++-%2300599C.svg?style=for-the-badge&logo=c%2B%2B&logoColor=white', 'C++'],
    ['https://img.shields.io/badge/Zig-%23F7A41D.svg?style=for-the-badge&logo=zig&logoColor=white', 'Zig'],
    ['https://img.shields.io/badge/-GraphQL-E10098?style=for-the-badge&logo=graphql&logoColor=white', 'GraphQL'],
    ['https://img.shields.io/badge/lua-%232C2D72.svg?style=for-the-badge&logo=lua&logoColor=white', 'Lua'],
    ['https://img.shields.io/badge/-Julia-9558B2?style=for-the-badge&logo=julia&logoColor=white', 'Julia'],
];

export const techStackFramework: Array<Array<string>> = [
    ['https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white', 'Kubernetes'],
    ['https://img.shields.io/badge/grafana-%23F46800.svg?style=for-the-badge&logo=grafana&logoColor=white', 'Grafana'],
    ['https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white', 'Git'],
    ['https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB', 'React'],
    ['https://img.shields.io/badge/vuejs-%2335495e.svg?style=for-the-badge&logo=vuedotjs&logoColor=%234FC08D', 'Vue'],
    ['https://img.shields.io/badge/astro-%232C2052.svg?style=for-the-badge&logo=astro&logoColor=white', 'Astro'],
    ['https://img.shields.io/badge/Flutter-%2302569B.svg?style=for-the-badge&logo=Flutter&logoColor=white', 'Flutter'],
    ['https://img.shields.io/badge/.NET-5C2D91?style=for-the-badge&logo=.net&logoColor=white', 'dotNET'],
    ['https://img.shields.io/badge/PyTorch-%23EE4C2C.svg?style=for-the-badge&logo=PyTorch&logoColor=white', 'PyTorch'],
    ['https://img.shields.io/badge/Matplotlib-%23ffffff.svg?style=for-the-badge&logo=Matplotlib&logoColor=black', 'Matplotlib'],
    ['https://img.shields.io/badge/Apache%20Hadoop-66CCFF?style=for-the-badge&logo=apachehadoop&logoColor=black', 'Hadoop'],
    ['https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white', 'Terraform'],
    ['https://img.shields.io/badge/ansible-%231A1918.svg?style=for-the-badge&logo=ansible&logoColor=white', 'Ansible'],
    ['https://img.shields.io/badge/Qt-%23217346.svg?style=for-the-badge&logo=Qt&logoColor=white', 'Qt'],
    ['https://img.shields.io/badge/-selenium-%43B02A?style=for-the-badge&logo=selenium&logoColor=white', 'Selenium'],
];
